<?php

namespace Slashx\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TypageController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Slashx\AdminBundle\Controller\TypageController();
        return $instance;
    }
}
