<?php

namespace Slashx\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhotographieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotographieRepository extends EntityRepository
{
}
