<?php

namespace Slashx\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypageRepository extends EntityRepository
{
}
